export const FETCH_SINGLE = 'FETCH_SINGLE';
export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
export const FETCH_SINGLE_ERROR = 'FETCH_SINGLE_ERROR';

export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';
export const FETCH_ALL_ERROR = 'FETCH_ALL_ERROR';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const NEW_RECORD = 'NEW_RECORD';
export const NEW_RECORD_SUCCESS = 'NEW_RECORD_SUCCESS';
export const NEW_RECORD_ERROR = 'NEW_RECORD_ERROR';
